[project]
name = "gpt-2-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.8.0",
]


[tool.ruff.lint]
select = ["ALL"]
